basePath = "./images/"

invite = basePath + "invite.png"
start = basePath + "start.png"
acceptDefaultInvite = basePath + "accept_default_invite.png"
confirm = basePath + "confirm.png"
createGroup1 = basePath + "create_group1.png"
createGroup2 = basePath + "create_group2.png"
defaultInvite = basePath + "default_invite.png"
enter1 = basePath + "enter1.png"
enter2 = basePath + "enter2.png"
fail = basePath + "fail.png"
group = basePath + "group.png"
hun11Btn = basePath + "hun11_btn.png"
hun11 = basePath + "hun11.png"
isInviteDefaultUncheck = basePath + "is_invite_default_uncheck.png"
notPrivate = basePath + "not_private.png"
vic1 = basePath + "vic1.png"